/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#39393b",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e1e4",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-container": "#10b981",
        "secondary": "#ffb77d",
        "on-secondary": "#4d2600",
        "tertiary": "#b7c8e1",
        "on-tertiary-container": "#2a3a4f",
        "secondary-container": "#d97707",
        "on-primary-fixed-variant": "#005236",
        "error-container": "#93000a",
        "on-primary-container": "#00422b",
        "error": "#ffb4ab",
        "primary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#ffb77d",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-on-surface": "#313032",
        "surface-dim": "#131315",
        "surface": "#131315",
        "on-primary": "#003824",
        "on-tertiary-fixed": "#0b1c30",
        "primary": "#4edea3",
        "primary-fixed-dim": "#4edea3",
        "on-background": "#e5e1e4",
        "secondary-fixed": "#ffdcc3",
        "surface-container-lowest": "#0e0e10",
        "on-error": "#690005",
        "tertiary-container": "#94a4bd",
        "surface-container-highest": "#353437",
        "background": "#131315",
        "on-primary-fixed": "#002113",
        "on-tertiary": "#213145",
        "on-secondary-container": "#432100",
        "inverse-primary": "#006c49",
        "on-surface-variant": "#bbcabf",
        "on-secondary-fixed": "#2f1500",
        "surface-tint": "#4edea3",
        "surface-container": "#201f22",
        "surface-variant": "#353437",
        "surface-container-high": "#2a2a2c",
        "outline": "#86948a",
        "surface-container-low": "#1c1b1d",
        "on-surface": "#e5e1e4",
        "outline-variant": "#3c4a42",
        "on-secondary-fixed-variant": "#6e3900",
        brand: {
          50: '#F0FDF4',
          100: '#DCFCE7',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
          800: '#065F46',
          900: '#064E3B',
        }
      },
      fontFamily: {
        serif: ['Newsreader', 'Georgia', 'serif'],
        display: ['Instrument Serif', 'Georgia', 'serif'],
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'label-micro-caps': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'data-mono': ['Inter', 'monospace'],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      }
    },
  },
  plugins: [],
}
