services:
  - type: web
    name: attendx-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_MASTER_PASSWORD
        value: Doomsday@1812
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://one-attendx.vercel.app,http://localhost:5173,http://localhost:3000"
      - key: STORAGE_DIR
        value: "/tmp/storage"
